apiVersion: v1
kind: Service
metadata:
  name: {{ include "kontakt.fullname" . }}-api
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kontakt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
