apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kontakt.fullname" . }}
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentRef.name }}
      {{- if .Values.gateway.parentRef.namespace }}
      namespace: {{ .Values.gateway.parentRef.namespace }}
      {{- end }}
  {{- if .Values.gateway.hostname }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: {{ include "kontakt.fullname" . }}-api
          port: {{ .Values.api.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /c
      backendRefs:
        - name: {{ include "kontakt.fullname" . }}-api
          port: {{ .Values.api.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /uploads
      backendRefs:
        - name: {{ include "kontakt.fullname" . }}-api
          port: {{ .Values.api.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "kontakt.fullname" . }}-web
          port: {{ .Values.web.port }}
