{{- if and (eq .Values.storage.driver "local") .Values.persistence.uploads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kontakt.fullname" . }}-uploads
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass | quote }}
  {{- end }}
{{- end }}
