{{- if and (not .Values.existingSecret) (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kontakt.fullname" . }}
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  JWT_SECRET: {{ .Values.app.jwtSecret | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc | quote }}
  {{- if eq .Values.storage.driver "s3" }}
  S3_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKeyId | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
