apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kontakt.fullname" . }}
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  JWT_SECRET: {{ .Values.app.jwtSecret | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc | quote }}
