{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kontakt.serviceAccountName" . }}
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
