apiVersion: v1
kind: Service
metadata:
  name: {{ include "kontakt.fullname" . }}-web
  labels:
    {{- include "kontakt.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kontakt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
